version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim  # Oracle 21c XE 버전
    container_name: oracle-db
    environment:
      - ORACLE_PASSWORD=1234  # Oracle 사용자 비밀번호 설정
    ports:
      - "1522:1521"  # 호스트와 컨테이너 간의 포트 연결
    volumes:
      - oracle-data:/opt/oracle/oradata  # 데이터를 유지하기 위한 볼륨 설정
    networks:
      - my-network

  spring-app:
    image: abysss/recode-master  # 이미 빌드된 Spring Boot JAR 파일이 있는 이미지
    container_name: spring-app
    depends_on:
      - oracle-db  # spring-app이 oracle-db에 의존함
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:1521/xe  # Oracle DB의 연결 URL (docker-compose 네트워크 사용)
      SPRING_DATASOURCE_USERNAME: recodeDB
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: oracle.jdbc.OracleDriver
    ports:
      - "8080:8080"  # 애플리케이션 포트
    networks:
      - my-network

volumes:
  oracle-data:

networks:
  my-network: