spring:
  application:
    name: recode

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    enabled: true

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: recodeDB
    password: 1234
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
    database: oracle
    database-platform: org.hibernate.dialect.OracleDialect

  # Email
  mail:
    host: smtp.gmail.com
    port: 587
    username: dlstoddyflcorj@gmail.com
    password: qvbvzqpiotjkqjnd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000
    sender-email: dlstoddyflcorj@gmail.com

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

jwt:
  secret: askd
  accessExp : 1800000 # 30 * 60 * 1000 밀리초 (30분)
  refreshExp : 180000000

logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
